---
# tasks file for nginx
- name: nginx server container
  docker:
    state: started
    name: nginx-server
    image: 'nginx:{{nginx_version}}'
    command: /bin/bash -c "envsubst < {{role_path}}/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports: 
    - "{{ nginx_docker_ports }}"
    volumes:
    - /projects/symfony:/var/www/symfony
    links: 
      - php-fpm-server:php-server
    env:
      NGINX_HOST: '{{nginx_default_host}}'    
      NGINX_PORT: '{{nginx_default_host}}'
    tty: true