---
# tasks file for nginx
- name: build image nginx
  docker_image:
    path: '{{role_path}}/docker'
    name: 'fobos/nginx'
    state: build
    tag: 1.9.10
- name: nginx server container
  docker:
    state: reloaded
    name: nginx-server
    image: 'fobos/nginx:1.9.10'
    hostname: '{{nginx_default_host}}'
    ports: 
    - "{{ nginx_docker_ports }}"
    volumes_from:
    - application-data
    links: 
      - php-fpm-server:php-server
    env:
      NGINX_HOST: '{{nginx_default_host}}'    
      NGINX_PORT: '{{nginx_default_host}}'
    tty: true