---
# tasks file for mysql
- name: mysql data container
  docker:
    name: mysql-data
    image: busybox
    state: present
    volumes: mysql_data_volumes

- name: mysql server container
  docker:
    state: started
    name: mysql-server
    image: 'mysql:{{mysql_version}}'
    ports: 
    - "{{ mysql_ports }}"
    volumes_from:
    - mysql-data
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: '{{mysql_root_password}}'
      MYSQL_ROOT_PASSWORD: '{{mysql_root_password}}'
      MYSQL_DATABASE: '{{mysql_database}}'
      MYSQL_USER: '{{mysql_user}}'
      MYSQL_PASSWORD: '{{mysql_password}}'
    tty: true  